README: update sponsors
monero-project/monero pull request #6833
Opened 2020-09-20 23:39 UTC by selsta

- http -> https
- remove outdated sponsors
- add new sponsors

2020-09-21 07:11 UTC, dEBRUYNE-1 approved these changes

2020-09-21 19:10 UTC, dEBRUYNE-1 approved these changes

2020-09-21 20:40 UTC, dEBRUYNE-1 approved these changes

2020-09-22 05:37 UTC, erciccione approved these changes

2020-10-07 22:29 UTC, jonathancross requested changes

2020-10-07 22:29 UTC, jonathancross commented on README.md
> +[<img width="150" src="https://www.getmonero.org/img/sponsors/symas.png"/>](https://www.symas.com/)
Should be `https://symas.com/` to prevent unnecessary redirect.

2020-10-07 22:29 UTC, jonathancross commented on README.md
> +[<img width="150" src="https://www.getmonero.org/img/sponsors/forked_logo.png"/>](https://www.forked.net/)
Hmmm... this URL doesn't load correctly over `https` in Chrome.

Their TLS cert is issued to `portal.forked.net` so it fails in the browser.  If you go to that domain over https, it 302 redirects to the _insecure_ version.
![image](https://user-images.githubusercontent.com/5115470/95394375-a6e8fd80-08fc-11eb-83df-4c8a9cd17548.png)

2020-10-07 23:45 UTC, selsta commented
@jonathancross done

2020-10-08 20:27 UTC, jonathancross approved these changes
Thanks!

2020-10-13 15:40 UTC, merged