cmake: fix ccache detection
monero-project/monero pull request #7413
Opened 2021-03-01 21:09 UTC by perfect-daemon

2021-03-02 08:23 UTC, mj-xmr requested changes

2021-03-02 08:23 UTC, mj-xmr commented on cmake/FindCcache.cmake
> +]=])
Please tabulate this block twice.

2021-03-02 08:24 UTC, mj-xmr commented
I have checked the logs. It appears to work properly. Everything works like before (of course FreeBSD's ccache is still failing, like before)

2021-03-02 09:09 UTC, perfect-daemon commented on cmake/FindCcache.cmake
> +]=])
```
Bracket argument can't be formatted due to limitations[0] of CMake language without affecting result.
[0] https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#bracket-argument
```

2021-03-02 09:11 UTC, selsta approved these changes
Fixes ccache detection on my Mac.

2021-03-02 09:13 UTC, mj-xmr commented on cmake/FindCcache.cmake
> +]=])
OK then.

2021-03-02 09:13 UTC, mj-xmr approved these changes

2021-03-17 12:04 UTC, selsta approved these changes

2021-03-20 05:49 UTC, merged