[release-v0.17] cmake: forbid and fix undefined symbols / multiple definitions
monero-project/monero pull request #7693
Opened 2021-04-27 12:31 UTC by selsta

See #7692

2021-04-28 17:17 UTC, mj-xmr approved these changes

2021-05-08 19:18 UTC, mj-xmr approved these changes

2021-07-13 05:59 UTC, mj-xmr requested changes
Here I wouldn't be very restrictive, but 2 things bother me:
- there are 3 commits, not 1
- one check didn't pass and a total of only 5 have even been ran.

2021-07-13 06:03 UTC, selsta commented
> there are 3 commits, not 1

It's intentional. These patches do separate things.

> one check didn't pass and a total of only 5 have even been ran.

This is the release branch. We don't have more checks here.

2021-07-13 06:20 UTC, mj-xmr commented
> > there are 3 commits, not 1
> 
> It's intentional. These patches do separate things. These are not "fixup" patches that should be squashed.
> 
> > one check didn't pass and a total of only 5 have even been ran.
> 
> This is the release branch. We don't have more checks here.

Ok, I didn't know. Then let's wait for the checks to finish.

2021-07-13 06:55 UTC, mj-xmr approved these changes

2021-07-27 20:53 UTC, merged