Ci ubuntu 18.04
monero-project/monero pull request #7769
Opened 2021-07-04 05:25 UTC by mj-xmr

A follow up of https://github.com/monero-project/monero/pull/7768 , where it was decided, that Ubuntu 18.04 shall be tested, but is a separate use case than Boost matrix use case. The Ubuntu 18.04 use case thus doesn't need the Boost matrix, and can be built with the default options.

Temp. info: This draft PR contains a commit to be reverted, taken from https://github.com/monero-project/monero/pull/7762 , which has to be merged first. Afterwards this PR will be published. The commit tests if the fix works.

2021-07-08 02:33 UTC, selsta commented
This should be closed with reference to #7770

2021-07-10 03:55 UTC, mj-xmr commented
> This should be closed with reference to #7770

For the record: these 2 PRs have become 2 distinctive things. This one tests for a generic Ubuntu 18 compatibility with all the default packages (read: no mentioning of Boost), while #7770 is about Boost specifically.

2021-07-10 03:56 UTC, selsta commented
Ok, it's fine keeping them separate. Please remove the Trezor test and the draft status.

2021-07-10 03:59 UTC, mj-xmr commented
> Ok, it's fine keeping them separate. Please remove the Trezor test and the draft status.

Will do soon, but stay adviced, that this will make the checks fail. As long as the PRs are merged in order, this will not be a problem, so please make an exception here.
@luigi1111 : FYI

2021-07-10 04:00 UTC, selsta commented
This will get merged later anyway.

2021-07-10 04:10 UTC, mj-xmr commented
Done.

2021-07-10 04:12 UTC, selsta requested changes
This should be a matrix with both 18.04 and 20.04 added to the existing `build-ubuntu` test.

2021-07-10 04:21 UTC, mj-xmr commented
> This should be a matrix with both 18.04 and 20.04 added to the existing `build-ubuntu` test.

OK will do.

2021-07-10 04:31 UTC, selsta commented on .github/workflows/build.yml
> +
unintended newline

2021-07-10 04:33 UTC, selsta approved these changes

2021-07-11 06:09 UTC, mj-xmr commented
@selsta : Shall I rebase and get the checks right, since #7762 has been merged?

2021-07-12 01:08 UTC, selsta commented
However you want.

2021-07-12 06:06 UTC, mj-xmr commented
So I rebased.

2021-07-12 21:47 UTC, selsta approved these changes

2021-07-27 20:59 UTC, merged