wallet2: protect client from divide by 0 caused by integer truncation
monero-project/monero pull request #7845
Opened 2021-08-11 13:54 UTC by j-berman

https://github.com/monero-project/monero/pull/7798#issuecomment-887141766

2021-08-16 08:27 UTC, mj-xmr commented
It looks OK from technical point if view (UB / div by 0).

No comment on the functionality side from me, unfortunately.

2021-08-16 08:33 UTC, mj-xmr commented
Not directly related, but there will be some truncation done [in line 1035](https://github.com/monero-project/monero/pull/7845/files#diff-04cf14f64d2023c7f9cd7bd8e51dcb32ed400443c6a67535cb0105cfa2b62c3cR1035):

`uint64_t output_index = x / average_output_time;`

In this case the output variable should be rounded first, then cast:

`uint64_t output_index = static_cast<uint64_t>(round(x / average_output_time));`

A candidate for a future PR / issue?

2021-08-16 08:40 UTC, mj-xmr requested changes

2021-08-16 08:40 UTC, mj-xmr commented on src/wallet/wallet2.cpp
> +  THROW_WALLET_EXCEPTION_IF(num_rct_outputs == 0 || outputs_to_consider == 0, error::wallet_internal_error, "No rct outputs");
One nitpick here would be that my prefference is:

```
THROW_WALLET_EXCEPTION_IF(num_rct_outputs == 0,      error::wallet_internal_error, "No rct outputs");
THROW_WALLET_EXCEPTION_IF(outputs_to_consider == 0, error::wallet_internal_error, "No rct outputs to consider");
```

2021-08-16 18:10 UTC, j-berman commented
> Not directly related, but there will be some truncation done [in line 1035](https://github.com/monero-project/monero/pull/7845/files#diff-04cf14f64d2023c7f9cd7bd8e51dcb32ed400443c6a67535cb0105cfa2b62c3cR1035):
> 
> `uint64_t output_index = x / average_output_time;`
> 
> In this case the output variable should be rounded first, and next cast (optionally, just to avoid warnings):
> 
> `uint64_t output_index = static_cast<uint64_t>(round(x / average_output_time));`
> 
> If rounding sounds like a bad idea, because it adds +1 to the index when the underlying value is >= 0.5, then `floor` should be used instead of `round` to make it more explicit what is expected from this line.
> 
> A candidate for a future PR / issue?

Agree with this! I'll submit a separate PR that uses `floor` for that exact circumstance :)

2021-08-18 05:47 UTC, mj-xmr approved these changes

2021-08-19 01:26 UTC, UkoeHB requested changes

2021-08-19 01:26 UTC, UkoeHB commented on src/wallet/wallet2.cpp
> +    average_output_time = DIFFICULTY_TARGET_V2 * blocks_to_consider / static_cast<double>(outputs_to_consider);
```suggestion
     // TODO: apply this to all cases; do so alongside a hard fork, where all clients will update at the same time, preventing anonymity puddle formation
    average_output_time = DIFFICULTY_TARGET_V2 * blocks_to_consider / static_cast<double>(outputs_to_consider);
```

2021-08-19 12:16 UTC, UkoeHB approved these changes

2021-08-19 12:50 UTC, mj-xmr commented
Once the code appears to be in a final stage, please squash to just 1 commit and rebase.

2021-08-19 12:51 UTC, selsta commented
There doesn't appear the need to rebase, squashing and force pushing should be fine.

2021-08-19 22:12 UTC, selsta approved these changes

2021-08-20 04:16 UTC, mj-xmr approved these changes

2021-08-20 20:45 UTC, merged