This is what actually seems to work correctly on ubuntu 20
monero-project/monero pull request #7901
Opened 2021-08-28 13:20 UTC by yablaAdmin

The libg* directory does not exist at the higher level.

```ubuntu@ip-X:/usr/src/gtest$ ls
CMakeCache.txt  CMakeLists.txt  Makefile   bin    cmake_install.cmake  include  samples  src
CMakeFiles      CONTRIBUTORS    README.md  cmake  docs                 lib      scripts  test
```

You can see that there is no libg here ^^^

2021-08-30 16:50 UTC, mj-xmr requested changes
The original solution still works under Debian stable. I checked whether Ubuntu works differently already, and you're right that it does. Therefore I'd suggest:


build the library binary manually. This can be done with the following command ```sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake . && sudo make```
Then:
On Debian:
`sudo mv libg* /usr/lib/`
On Ubuntu:
`sudo mv lib/libg* /usr/lib/`

2021-08-30 19:05 UTC, ralphmapper commented
@mj-xmr  
I made the edit you suggested.  Thanks!

2021-08-30 19:21 UTC, mj-xmr commented
Great. Looks fine.

Unless others have some comments in near time, please squash and force-push.

2021-09-12 03:53 UTC, selsta commented
Do you know how to squash your commits?

2021-09-17 15:27 UTC, mj-xmr commented
@ralphmapper  if you have troubles with git or sth., I'd gladly take over the PR and do it for you, obviously setting you as the author.

2021-09-18 11:31 UTC, ralph-sionlineny commented
@mj-xmr please go ahead and merge. I see a message which says that I don't have right access. 

![Screenshot_20210918_073105_com android chrome](https://user-images.githubusercontent.com/24529023/133887340-72e0905e-fd67-497b-b397-0b57fd6e8a3f.jpg)

2021-09-18 11:52 UTC, mj-xmr commented
> @mj-xmr please go ahead and merge. I see a message which says that I don't have right access.

Done here: https://github.com/monero-project/monero/pull/7954. Please cross check. I'm not sure if I set the author right. I'm a bit confused with the multiple accounts.

2021-09-18 16:06 UTC, ralph-sionlineny commented
Thank you if you could change the author to @ralphmapper that other account was an accident.

2021-09-18 16:28 UTC, yablaAdmin commented
> Thank you if you could change the author to @ralphmapper that other account was an accident.

Yes @ralphmapper is correct.  If you can make @ralphmapper the author.  Thanks!

2021-09-18 16:59 UTC, mj-xmr commented
> Thank you if you could change the author to @ralphmapper that other account was an accident.

I need to know the email address, that I have to set there. A Github alias is fine.

2021-09-18 18:03 UTC, ralphmapper commented
> > Thank you if you could change the author to @ralphmapper that other account was an accident.
> 
> I need to know the email address, that I have to set there. A Github alias is fine.

https://github.com/ralphmapper  The email address is ralphmapper@gmail.com

2021-09-18 18:18 UTC, mj-xmr commented
Done. Please go to https://github.com/monero-project/monero/pull/7954 and cross check.

I advise you to remove your email now from your previous comment to avoid being spammed :)

2021-09-23 19:47 UTC, selsta commented
Continue in #7954

2021-09-23 19:47 UTC, closed without merging