Build raspberry pi
monero-project/monero pull request #7946
Opened 2021-09-15 11:20 UTC by ArqTras

Make release-rpi for NO_AES rpi binaries

2021-09-15 12:06 UTC, selsta commented
Please also update the Raspberry part of the README.

2021-09-16 12:05 UTC, mj-xmr commented on Makefile
> +	cd $(builddir)/release-rpi && cmake -D NO_AES=ON -D BUILD_TESTS=OFF -D CMAKE_BUILD_TYPE=Release $(topdir) && $(MAKE)
`BUILD_TESTS` is `OFF` by default. I see no reason to disable it explicitly, especially since the default `release` target does it neither.

2021-09-16 12:06 UTC, mj-xmr requested changes
Please remove `-D BUILD_TESTS=OFF`, then squash the commits.

2021-09-16 19:44 UTC, ArqTras commented
messed

2021-09-16 19:44 UTC, closed without merging