readme: arch/fedora deps + small fixes
monero-project/monero pull request #8281
Opened 2022-04-23 01:57 UTC by hinto-janaiyo

hi again, just a few more small changes:

- added arch/fedora deps code blocks
- `v0.17.1.0` > `v0.17.3.0`
- blockchain size + date update (wow its been 2 years!)
- misc. fixes

3fa95a8 deletes the redundant 8-address for donations.  
Was there a reason why both addresses were listed? (maybe for sorting donations?)

2022-04-23 06:46 UTC, selsta approved these changes

2022-04-23 14:40 UTC, hinto-janaiyo commented
reverted `git checkout v0.17.3.0` to `git checkout release-v0.17`  
since the line above it specifies "change to the most recent release branch, and build"

2022-04-23 19:25 UTC, hinto-janaiyo commented
I think the dependency list for Fedora is missing `gcc-c++` and a few other packages, can't compile Monero on it

Added `python3` since Arch and bare-bones Debian don't come with it

2022-04-25 00:41 UTC, selsta approved these changes

2022-04-26 18:24 UTC, tobtoht approved these changes

2022-04-28 13:41 UTC, mj-xmr commented on README.md
> +`888tNkZrPN6JsEgekjMnABU4TBzc2Dt29EPAvkRxbANsAnjyPbb3iQ1YBRk1UXcdRsiKc9dhwMVgN5S9cQUiyoogDavup3H`
I double checked if there were any changes / typos in the addresses and there weren't any. But next time I'd ask rather not to touch such lines.

2022-04-28 13:42 UTC, mj-xmr requested changes
Other than the `python3` change, it's fine.

2022-04-28 21:24 UTC, selsta approved these changes

2022-04-28 21:47 UTC, tobtoht approved these changes

2022-05-01 05:59 UTC, mj-xmr approved these changes
Rechecked the addresses.

2022-05-07 18:15 UTC, selsta approved these changes

2022-05-10 21:51 UTC, merged