disable multisig by default
monero-project/monero pull request #8328
Opened 2022-05-14 19:53 UTC by moneromooo-monero

There are vulnerabilities in multisig protocol if the parties do not
trust each other, and while there is a patch for it, it has not been
throroughly reviewed yet, so it is felt safer to disable multisig by
default for now.
If all parties in a multisig setup trust each other, then it is safe
to enable multisig.

2022-05-14 20:27 UTC, kayabaNerve commented
Can the flag itself communicate this is unsafe? enable-unsafe-multisig? enable-multisig-experimental? etc

I think the former is more accurate if this will be applied to the existing multisig protocol as well as the new one, whereas the latter makes sense for just the new one.

2022-05-15 05:58 UTC, rbrunner7 commented on src/simplewallet/simplewallet.cpp
>    prepare_multisig_main(args, false);
Well, if there is a `main` method in addition to the direct method for interactive use that one will already check for multisig enabled, so strictly speaking a number of such checks are superfluous, but maybe it's a good idea to have them nevertheless so it's crystal clear there is a check and everybody reading the code sees this as early as possible.

2022-05-15 05:59 UTC, rbrunner7 commented
I reviewed, and it looks good, but I wonder why there seems to be no info or warning to the user **why** multisig is disabled by default anywhare at any time. The new macro `CHECK_MULTISIG_ENABLED` in `simplewallet.cpp` simply tells now:

    Multisig is disabled, you can enable it with:
       set enable-multisig 1

Do you wait for a good message formulated by @UkoeHB to add in order to complete the PR with it?

2022-05-15 08:54 UTC, moneromooo-monero commented
I can change the message if I get one, yes.
The extra checks won't get you two messages, due to the early out. I don't particularly want to verify whether every one can be called only via the top level one.

2022-05-16 22:18 UTC, UkoeHB requested changes
I agree with @kayabaNerve that `experimental` cleanly communicates why multisig needs to be enabled. Sorry that my semantic recommendations might cause a big diff compared to the existing commit (I didn't suggest changes for all cases, only the main ones).

2022-05-16 22:18 UTC, UkoeHB commented on src/simplewallet/simplewallet.cpp
> +    success_msg_writer() << "enable-multisig = " << m_wallet->enable_multisig();
```suggestion
    success_msg_writer() << "enable-multisig-experimental = " << m_wallet->enable_multisig();
```

2022-05-16 22:18 UTC, UkoeHB commented on src/simplewallet/simplewallet.cpp
> +    CHECK_SIMPLE_VARIABLE("enable-multisig", set_enable_multisig, tr("0 or 1"));
```suggestion
    CHECK_SIMPLE_VARIABLE("enable-multisig-experimental", set_enable_multisig, tr("0 or 1"));
```

2022-05-16 22:18 UTC, UkoeHB commented on src/wallet/wallet2.h
> +    bool enable_multisig() const { return m_enable_multisig; }
```suggestion
    bool multisig_is_enabled() const { return m_enable_multisig; }
```
Can you disambiguate the two functions here? One `enables` and the other asks `is it enabled?`.

2022-05-16 22:18 UTC, UkoeHB commented on src/wallet/wallet2.h
> +    bool m_enable_multisig;
```suggestion
    bool m_multisig_enabled;
```
`enable` is a verb, `enabled` is an adjective

2022-05-16 22:18 UTC, UkoeHB commented on src/wallet/wallet_rpc_server.cpp
> +      er.message = "This wallet is multisig, and multisig is disabled. You can enable it by running this once in monero-wallet-cli: set enable-multisig 1"; \
```suggestion
      er.message = "This wallet is multisig, and multisig is disabled. You can enable it by running this once in monero-wallet-cli: set enable-multisig-experimental 1"; \
```

2022-05-16 22:18 UTC, UkoeHB commented on src/wallet/wallet_rpc_server_commands_defs.h
> +      bool enable_multisig;
```suggestion
      bool enable_multisig_experimental;
```
For any user-facing API, add the experimental qualifier.

2022-05-16 22:18 UTC, UkoeHB commented on src/wallet/wallet_rpc_server_error_codes.h
> +#define WALLET_RPC_ERROR_CODE_DISABLED               -48
```suggestion
#define WALLET_RPC_ERROR_CODE_MULTISIG_DISABLED      -48
```

2022-05-16 22:18 UTC, UkoeHB commented on utils/python-rpc/framework/wallet.py
> +                'enable_multisig': enable_multisig,
```suggestion
                'enable_multisig_experimental': enable_multisig_experimental,
```

2022-05-17 17:30 UTC, UkoeHB commented
Here is a blurb about multisig (not sure exactly where/how you want to use it).

```
Multisig is an experimental feature and may have bugs. Things that could go wrong include: funds sent to a multisig wallet can't be spent at all, funds can only be spent with the participation of a malicious group member, funds can be stolen by a malicious group member.
```

2022-05-17 19:04 UTC, rbrunner7 approved these changes
Personally I find the name of the option and the warning about the possible bugs a bit drastic, but hey, better err on the side of caution.

2022-05-17 19:48 UTC, UkoeHB requested changes
minor additional comments

2022-05-17 19:48 UTC, UkoeHB commented on src/wallet/wallet_rpc_server.cpp
> +      er.message = "This wallet is multisig, and multisig is disabled. Multisig is an experimental feature and may have bugs. Things that could go wrong include: funds sent to a multisig wallet can't
```suggestion
      er.message = "This wallet is multisig, and multisig is disabled. Multisig is an experimental feature and may have bugs. Things that could go wrong include: funds sent to a multisig wallet can't be spent at all, can only be spent with the participation of a malicious group member, or can be stolen by a malicious group member. You can enable it by running this once in monero-wallet-cli: set enable-multisig-experimental 1"; \
```
typo

2022-05-17 19:48 UTC, UkoeHB commented on src/wallet/wallet_rpc_server_error_codes.h
> +#define WALLET_RPC_ERROR_CODE_DISABLED               -48
For `WALLET_RPC_ERROR_CODE_DISABLED` are you trying to add a generic 'disabled' code, or should it be `WALLET_RPC_ERROR_CODE_MULTISIG_DISABLED`?

2022-05-17 19:52 UTC, moneromooo-monero commented
Yes, there's no particularly good reason to restrict it to multisig really.

2022-05-17 19:53 UTC, UkoeHB approved these changes
Thanks

2022-05-27 02:23 UTC, merged