build: prepare v0.18.0.0
monero-project/monero pull request #8425
Opened 2022-07-06 21:50 UTC by selsta

2022-07-07 20:37 UTC, hyc commented on README.md
> +| 2210000                        | 2020-10-17 | v13               | v0.17.0.0              | v0.18.0.0                  | New CLSAG transaction format
Why did these two lines change?

2022-07-12 00:43 UTC, plowsof commented
i ran this command on my own blockchain lmdb file (providing the correct `--data-dir` if needed):
```
./monero-blockchain-export --output-file checkpoints.dat --block-stop 2661600 --blocksdat
```
confirmed the checksum of the checkpoints file matches that of this PR:
```
$ shasum -a256 checkpoints.dat
e9371004b9f6be59921b27bc81e28b4715845ade1c6d16891d5c455f72e21365  checkpoints.dat
```
also confirmed the hash of blockheight 2661600 has the correct hash listed [here](https://xmrchain.net/search?value=41c9060e8426012238e8a26da26fcb90797436896cc70886a894c2c560bcccf2)

LGTM

2022-07-12 00:51 UTC, plowsof approved these changes

2022-07-12 02:33 UTC, jeffro256 approved these changes
Checkpoints.dat checks out, as well as the various misc changes

2022-07-13 12:59 UTC, hundehausen reviewed
Lines 141 + 142 of README.md must be changed to the new dates

2022-07-13 16:39 UTC, nahuhh requested changes
README.md line 141/142 have incorrect heights and dates
Example of correction: https://github.com/monero-project/monero/pull/8431

2022-07-13 17:15 UTC, hundehausen commented
Here is a new [PR](https://github.com/selsta/monero/pull/1)

2022-07-14 01:46 UTC, nahuhh approved these changes
Looks good

2022-07-15 15:24 UTC, merged