RandomX: print VM allocation warnings only once
monero-project/monero pull request #8705
Opened 2023-01-11 18:16 UTC by SChernykh

To reduce warning spam when large pages are unavailable.

2023-01-11 18:28 UTC, selsta commented
I'd prefer if this would get moved to info level log.

On macOS there is no way to remove this warning, we already use `VM_FLAGS_SUPERPAGE_SIZE_2MB` in RandomX which is the macOS equivalent for huge pages.

2023-01-11 18:34 UTC, SChernykh commented
> On macOS there is no way to remove this warning

I googled a bit and it seems you just need to to run with `sudo` or whatever it's called on macOS. Not a solution for everyone though.

2023-01-14 07:25 UTC, jeffro256 requested changes

2023-01-14 07:25 UTC, jeffro256 commented on src/crypto/rx-slow-hash.c
> +    }
```suggestion
#ifndef __APPLE__
    static int shown = 0;
    if (!shown) {
        shown = 1;
        mwarning(RX_LOGCAT, "Couldn't allocate RandomX full VM using large pages (will print only once)");
    }
#endif
```

2023-01-14 07:25 UTC, jeffro256 commented on src/crypto/rx-slow-hash.c
> +    static int shown = 0;
same here

2023-01-14 08:59 UTC, SChernykh commented
@selsta @jeffro256 I combined both your proposals in the second commit. This should work well for everyone.

2023-01-14 17:12 UTC, hyc commented
Are you sure MacOS hugepages aren't usable? They should still be supported on x86, even though there's no support on aarch64.

2023-01-14 17:24 UTC, SChernykh commented
We do use `VM_FLAGS_SUPERPAGE_SIZE_2MB` in virtual_memory.c for RandomX, so it should work on MacOS when run with sudo, but @selsta says it doesn't work. I don't have anything from Apple, so I can't check.

2023-01-14 17:25 UTC, selsta commented
I tested on aarch64, will check again with x86.

2023-01-14 17:36 UTC, hyc commented
Yeah, there are docker images to boot MacOS on a regular PC, but they only work with actual Intel CPUs, compatible to the models Apple used. I only have AMD CPUs here.

2023-01-17 11:01 UTC, plowsof commented
can we have this at log level 1 please, this caused me emotional distress because i thought my monerod was secretly mining and when e.g. running blockchain-stats i see the warning in the output:
```
# DATA
Date	Blocks/day	Blocks	Txs/Day	Txs	Bytes/Day	Bytes
2023-01-17 10:45:35.798	W Couldn't allocate RandomX cache using large pages
2023-01-12	423	2798323	10478	10478	26770465	26770465
2023-01-13	688	2799011	15464	25942	38953621	65724086
2023-01-14	774	2799785	15034	40976	38456559	104180645
2023-01-15	684	2800468	14076	55052	35789881	139970526
```

2023-01-17 17:16 UTC, SChernykh commented
I've changed large page allocation messages back to `mdebug` (the same as it was before the refactoring in #8677)

2023-01-17 18:08 UTC, selsta approved these changes

2023-02-06 17:35 UTC, merged