[seraphis] common: update TimingsDatabase
monero-project/monero pull request #8920
Opened 2023-06-28 15:25 UTC by UkoeHB

This is a PR in my 'upstreaming seraphis_lib project', the changes here are not used anywhere yet.

- Save data points in csv format.
- Support incremental saving.

### Usage

In test `init()` methods:
```
if (params.core_params.td.get())
{
    TimingsDatabase::instance null_instance;
    null_instance.npoints = 0;

    std::string report_csv;
    std::string separator{','};
    report_csv += std::to_string(param_a) + separator;
    report_csv += std::to_string(param_b) + separator;

    params.core_params.td->add(report_csv.c_str(), null_instance);
}
```

In `tests/performance_tests/main.cpp`:
```
TEST_PERFORMANCE0(filter, p, test_1);
TEST_PERFORMANCE0(filter, p, test_2);

if (p.core_params.td.get())
  p.core_params.td->save(false);
```

Output recorded in file:
```
param_a,param_b,{comma-separated timings database stats}  //test_1
param_a,param_b,{comma-separated timings database stats}  //test_2
```

2023-07-27 14:40 UTC, vtnerd requested changes

2023-07-27 14:40 UTC, vtnerd commented on src/common/timings.cc
> +        current_time += std::to_string(utc_time->tm_year + 1900) + '-';
I _think_ this can all be done with `strftime`:

```c++
std::strftime(out, max_size, "%F %T", sys_time);
```
```

2023-07-27 14:40 UTC, vtnerd commented on src/common/timings.cc
> +      fprintf(f, "%lu,", (unsigned long)i.second.t);
Its _probably_ more efficient to collapse these into one `fprintf` call, but that may mean worse formatting of the code.

2023-07-27 14:40 UTC, vtnerd commented on src/common/timings.cc
> +    if (i.first != name)
How often is this function called? This is now `O(n)` since its not in a map object.

2024-03-08 15:55 UTC, jeffro256 commented on src/common/timings.h
> +  std::list<std::pair<std::string, instance>> instances;
Why not just do a `std::sort` on save then?

2024-03-08 22:04 UTC, vtnerd approved these changes
Sorry @UkoeHB I missed you poking me earlier.

2024-05-21 03:47 UTC, merged