[seraphis] seraphis_crypto: add seraphis transcript utility
monero-project/monero pull request #8990
Opened 2023-09-10 21:39 UTC by UkoeHB

## Summary

This is a PR in my 'upstreaming seraphis_lib project', it is not used anywhere yet.

- Adds `src/seraphis_crypto` directory. Includes a dummy cpp file so cmake won't complain (will remove it once I have a cpp file to add).
- Adds `sp_transcript.h` to `seraphis_crypto`.

## Explanation

In the current codebase, transcripting of crypto protocols is done manually which is verbose and inflexible. I wrote a transcripting utility that is quite ergonomic and has served me well in the seraphis library.

There are two modes
- `SpFSTranscript`: Fiat-Shamir transcript, includes labels, type flags, and type lengths. Suited for variable-length transcripts. Should be used for Fiat-Shamir challenges.
- `SpKDFTranscript`: KDF transcript, does not include labels, type flags, or type lengths. Suited for short fixed-length transcripts (e.g. key derivations). In my seraphis library all uses of KDF transcripts are less than 128 bytes (or 256 bytes at least, can't remember).

Example use:
```cpp
// my_proof.h
struct MyProof
{
    rct::key A;
};
inline const boost::string_ref container_name(const MyProof&) { return "MyProof"; }
void append_to_transcript(const MyProof &container, SpTranscriptBuilder &transcript_inout);

// my_proof.cpp
void append_to_transcript(const MyProof &container, SpTranscriptBuilder &transcript_inout)
{
    transcript_inout.append("A", container.A);
}

// build a transcript and consume it
rct::key make_challenge(const proof &P)
{
    // hash data
    SpFSTranscript transcript{config::HASH_KEY_MY_CHALLENGE, sizeof(rct::key)};
    transcript.append("proof", proof);

    // challenge
    rct::key challenge;
    sp_hash_to_scalar(transcript.data(), transcript.size(), challenge.bytes);

    return challenge;
}
```

2023-09-11 00:43 UTC, vtnerd requested changes
Looks good, but there is one thing that definitely needs to be changed (the signed integer code).

2023-09-11 01:09 UTC, vtnerd requested changes
Oops, I thought this wasn't  submitted.

2023-09-11 01:49 UTC, vtnerd commented on src/seraphis_crypto/sp_transcript.h
> +            this->append_uint(static_cast<std::uint64_t>(-signed_integer));
Oh I didn't think of that. You'd have a positive and negative zero.

2023-10-13 18:48 UTC, selsta commented
@vtnerd could you re-review and potentially approve?

2023-10-14 23:39 UTC, vtnerd approved these changes

2023-10-14 23:39 UTC, vtnerd commented on src/seraphis_crypto/sp_transcript.h
> +#include "crypto/x25519.h"
I can't find this header, is this new? The checks still pass, so I must be missing something.

2023-11-05 03:02 UTC, selsta approved these changes

2023-11-06 14:25 UTC, merged