remove repetitive word
monero-project/monero pull request #9215
Opened 2024-03-07 06:03 UTC by cuinix

2024-03-07 16:18 UTC, jeffro256 requested changes

2024-03-07 16:18 UTC, jeffro256 commented on tests/gtest/src/gtest.cc
> -// The following two functions only make sense if the the system
This is an upstream file. We shouldn't touch it

2024-03-07 16:18 UTC, jeffro256 commented on external/db_drivers/liblmdb/mdb.c
> - * @param[in,out] fname	Path from from #mdb_fname_init().  A suffix is
This file is also supposed to match an upstream repo. We shouldn't touch it

2024-04-22 14:16 UTC, selsta approved these changes

2024-04-27 18:38 UTC, hinto-janai approved these changes

2024-05-21 15:33 UTC, jeffro256 approved these changes

2024-06-16 07:25 UTC, cuinix commented
friendly ping~

2024-07-16 22:31 UTC, merged