functional_tests: test HTTP digest authentication
monero-project/monero pull request #9245
Opened 2024-03-12 04:59 UTC by jeffro256

Test:
  1. Can't login to RPC server with --rpc-login enabled, but no auth provided
  2. Can access RPC server with correct login
  3. Can use internal HTTP client to access RPC server with correct login

With commit 0ae5c91e504b8007dedc2b89c9b2b49c404ffec6 not reverted, we fail test 3.

2024-03-14 10:21 UTC, 0xFFFC0000 requested changes
Without reverting the `0ae5c91`, it fails:

```
Attempting to connect to daemon loginless with RPC digest authentication required...
Attempting to connect to wallet server loginless with RPC digest authentication required...
Connecting to daemon with RPC digest authentication required...
Traceback (most recent call last):
  File "/home/xfffc/dev/monero-master/tests/functional_tests/http_digest_auth.py", line 110, in <module>
    HttpDigestAuthTest().run_test()
  File "/home/xfffc/dev/monero-master/tests/functional_tests/http_digest_auth.py", line 51, in run_test
    self.make_daemon_conn()
  File "/home/xfffc/dev/monero-master/tests/functional_tests/http_digest_auth.py", line 76, in make_daemon_conn
    self.daemon = Daemon(idx = DAEMON_IDX, username = DAEMON_USER, password = DAEMON_PASS)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Daemon.__init__() got an unexpected keyword argument 'username'
[TEST FAILED] http_digest_auth
```

Bue even after I reverted `0ae5c91`, I still fail: 

```
[TEST STARTED] http_digest_auth
Attempting to connect to daemon loginless with RPC digest authentication required...
Attempting to connect to wallet server loginless with RPC digest authentication required...
Connecting to daemon with RPC digest authentication required...
Traceback (most recent call last):
  File "/home/xfffc/dev/monero-master/tests/functional_tests/http_digest_auth.py", line 110, in <module>
    HttpDigestAuthTest().run_test()
  File "/home/xfffc/dev/monero-master/tests/functional_tests/http_digest_auth.py", line 51, in run_test
    self.make_daemon_conn()
  File "/home/xfffc/dev/monero-master/tests/functional_tests/http_digest_auth.py", line 76, in make_daemon_conn
    self.daemon = Daemon(idx = DAEMON_IDX, username = DAEMON_USER, password = DAEMON_PASS)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Daemon.__init__() got an unexpected keyword argument 'username'
[TEST FAILED] http_digest_aut
```

Tried this test separately, and still fails: 

```
/usr/bin/python3 "/home/xfffc/dev/monero/tests/functional_tests/functional_tests_rpc.py" "/usr/bin/python3" "/home/xfffc/dev/monero/tests/functional_tests" "/home/xfffc/dev/monero/build" "http_digest_auth"
```

2024-03-14 14:20 UTC, jeffro256 commented
Are you sure you included all the changes of this commit in that second run? That error would pop up if you only applied the changes to tests/functional_tests and not utils

2024-04-22 21:07 UTC, 0xFFFC0000 commented
Apologies for my late reply. 

After debugging the python script **it turns out you should not have `http_proxy` and `HTTP_PROXY` environment variables when you are running `functional_tests`.** 

Without reverting the `0ae5c91`: 
```
6: [TEST STARTED] http_digest_auth
6: Attempting to connect to daemon loginless with RPC digest authentication required...
6: Attempting to connect to wallet server loginless with RPC digest authentication required...
6: Connecting to daemon with RPC digest authentication required...
6: Connecting to wallet server with RPC digest authentication required...
6: Telling login-required daemon to start mining through login-required wallet server...
6: Traceback (most recent call last):
6:   File "/home/0xfffc/dev/monero/tests/functional_tests/http_digest_auth.py", line 110, in <module>
6:     HttpDigestAuthTest().run_test()
6:   File "/home/0xfffc/dev/monero/tests/functional_tests/http_digest_auth.py", line 54, in run_test
6:     self.mine_through_wallet()
6:   File "/home/0xfffc/dev/monero/tests/functional_tests/http_digest_auth.py", line 92, in mine_through_wallet
6:     self.wallet.start_mining(2)
6:   File "/home/0xfffc/dev/monero/utils/python-rpc/framework/wallet.py", line 1065, in start_mining
6:     return self.rpc.send_json_rpc_request(start_mining)
6:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6:   File "/home/0xfffc/dev/monero/utils/python-rpc/framework/rpc.py", line 85, in send_json_rpc_request
6:     return self.send_request("/json_rpc", inputs, 'result')
6:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6:   File "/home/0xfffc/dev/monero/utils/python-rpc/framework/rpc.py", line 77, in send_request
6:     assert 'error' not in res, res
6: AssertionError: {'error': {'code': -1, 'message': "Couldn't start mining due to unknown error."}, 'id': '0', 'jsonrpc': '2.0'}
6: [TEST FAILED] http_digest_auth
```

I confirm with this PR, that we do not have `functional_tests` error if we revert `0ae5c91`.

```
6: [TEST STARTED] http_digest_auth
6: Attempting to connect to daemon loginless with RPC digest authentication required...
6: Attempting to connect to wallet server loginless with RPC digest authentication required...
6: Connecting to daemon with RPC digest authentication required...
6: Connecting to wallet server with RPC digest authentication required...
6: Telling login-required daemon to start mining through login-required wallet server...
6: Waiting a few seconds for mining to occur...
6: Telling login-required daemon to stop mining through login-required wallet server...
6: Mined 13 blocks!
6: [TEST PASSED] http_digest_auth
```

2024-04-22 21:08 UTC, 0xFFFC0000 approved these changes

2024-05-21 04:26 UTC, merged