wallet2: move wallet error on RPC resp handling to wallet_errors file
monero-project/monero pull request #9380
Opened 2024-06-24 23:57 UTC by j-berman

Supports consistent RPC error response handling between wallet2 and a new wallet lib

Credit to @jeffro256 for identifying the source of a syntax issue

Used in the Seraphis lib async scanner: https://github.com/UkoeHB/monero/pull/23

2024-06-25 00:41 UTC, vtnerd requested changes

2024-06-25 00:41 UTC, vtnerd commented on src/wallet/wallet_errors.h
> +    static inline void throw_on_rpc_response_error(bool r, const epee::json_rpc::error &error, const std::string &status, const char *method)
Again, I would drop the `static` keyword here. This one should arguably be in a cpp anyway.

2024-06-25 00:56 UTC, vtnerd approved these changes

2024-08-13 16:49 UTC, luigi1111 commented
@j-berman please rebase

2024-12-04 12:55 UTC, 0xFFFC0000 approved these changes

2024-12-23 15:28 UTC, merged