chore: fix some comments
monero-project/monero pull request #9386
Opened 2024-06-26 07:52 UTC by haouvw

2024-06-26 15:56 UTC, vtnerd approved these changes

2024-06-29 04:16 UTC, jeffro256 requested changes

2024-06-29 04:16 UTC, jeffro256 commented on tests/gtest/include/gtest/gtest.h
> +  // These classes and functions are friends as they need to access private
This is an upstream file and should not be modified.

2024-07-14 18:22 UTC, selsta approved these changes

2024-07-16 23:01 UTC, merged