ci: msys2: pin boost to 1.86.0
monero-project/monero pull request #9623
Opened 2024-12-16 23:48 UTC by tobtoht

- Boost >= 1.87.0 breaks builds (#9596)
- MSYS2 ships Boost 1.87.0
- Temporary downgrade to get CI to pass until a proper fix is in place

2024-12-17 00:09 UTC, selsta approved these changes

2024-12-17 04:49 UTC, jeffro256 requested changes
Can we put an integrity check here please? Perhaps just a `sha256sum` or a PGP verify or something?

2024-12-17 16:19 UTC, x64x2 reviewed
ueh

2024-12-20 19:24 UTC, vtnerd requested changes

2024-12-20 19:24 UTC, vtnerd commented on .github/workflows/build.yml
> +        curl -O https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-boost-1.86.0-7-any.pkg.tar.zst.sig
Should a sha256 hash computation be done here?

2024-12-20 20:23 UTC, tobtoht commented
Using sha256 hash verification instead of gpg, as the latter would allow an attacker that has access to the msys2 repo to trick us into installing _any_ signed package. 

Assuming the release signing key isn't compromised (in which case everything is compromised), this would effectively allow an attacker to cause an older version of Boost to be installed while still passing CI. The older version of Boost could have a vulnerability that is not present in 1.86.0, and someone could unwittingly decide to run this development build outside of a testing environment.

I'm also downgrading `boost-libs` here as this package is required by `boost`, and the versions should not mismatch.

2024-12-21 03:27 UTC, selsta approved these changes
The files built don't get uploaded anyway so I don't think there is a legitimate attack vector here

2024-12-21 10:54 UTC, tobtoht commented
Ah right, it's the depends build that gets uploaded as an artifact, not this one. So yeah, the purpose of this job is only to check if Monero successfully builds on msys2.

2024-12-23 16:07 UTC, merged