Check for windows NTFS compression on monerod startup (fixes #9617)
monero-project/monero pull request #9664
Opened 2024-12-30 10:35 UTC by eversinc33

Fixes #9617

If the data-dir is compressed and the lmdb folder is (check for both, because if data-dir is compressed and lmdb doesnt exist yet, it is likely that the compression is configured to be applied recursively):

![image](https://github.com/user-attachments/assets/7f7394b0-4683-4e60-84af-661f0dde3301)

If just the db folder is compressed:

![image](https://github.com/user-attachments/assets/9c6b5e64-f722-4d9c-ba48-e6735ede6b3a)

If not compressed at all:

![image](https://github.com/user-attachments/assets/10b5e309-a1c7-4531-b8d6-5e96fdc9791f)

Just logging an ERROR message, just like if Fat32 is used, not aborting, because for a small blockchain this not be a critical issue. 

Can we assume that "lmdb" stays the name of the db folder? Since it is hardcoded here. Otherwise, one would need to define it somewhere central. I assumed so, because `BlockchainLMDB::get_db_name()` also has it hardcoded.

2024-12-30 13:17 UTC, nahuhh commented
Should probably only need to check the `data-dir/lmdb`

example `.bitmonero/lmdb`.

> Can we assume that "lmdb" stays the name of the db folder?

Testnet & stagenet will end up in subfolders like `.bitmonero/testnet/lmdb`

2024-12-30 14:28 UTC, eversinc33 commented
> Should probably only need to check the `data-dir/lmdb`

If there is no edge case where data-dir` is created, but `lmdb` isnt yet, sure.

> Testnet & stagenet will end up in subfolders like `.bitmonero/testnet/lmdb`

That is taken care of with `data_dir / "lmdb"`

2024-12-30 19:18 UTC, eversinc33 commented
Changed so that only the database directory is checked, and if it doesnt exist, it falls back to checking the data-dir.

2024-12-30 20:19 UTC, iamamyth commented
Either the software supports a compressed database/data dir, or it doesn't (I'm not certain as to the policy here, though compression + memory mapping seems like a bad idea); logging an ERROR and proceeding with startup doesn't make sense to me, and doesn't "fix" much of anything.

2024-12-30 20:48 UTC, eversinc33 commented
My reasoning was that this error only seems to become a problem if the blockchain exceeds 70GB (see https://github.com/monero-project/monero/issues/9569#issuecomment-2539368523), so its not a reason to halt if e.g. running for a smaller chain such as the testnet (or if the on disk chain becomes smaller in the future due to e.g. further pruning improvements). Im very open to discussions as I am just getting familiar with the codebase.

2024-12-30 22:29 UTC, iamamyth commented
I think you're on the right track here, but, conceptually, the blockchain grows forever, so allowing startup in a configuration which will eventually break wastes the feature detection and proves quite irritating for users (mainnet is the most critical use case and it exceeds the failure threshold). I may have uncovered the underlying problem: "If you compress a file that is larger than 30 gigabytes, the compression may not succeed." (https://learn.microsoft.com/en-us/windows/win32/fileio/file-compression-and-decompression). Rather than simply warning the user, or aborting, I suggest transparently fixing the problem in the BlockchainLMDB class:

1. When creating the data directory in `open`, disable compression on the directory.
2. (Maybe) If the db file exists and is compressed, prior to mdb_env_open, disable compression on the db file. This would fix existing databases going forward, and may also guard against "manual surgery" cases where users put the system into an effectively broken state by fiddling with file attributes.

You can find info on the relevant windows APIs here:
* Setting directory compression state: https://learn.microsoft.com/en-us/windows/win32/fileio/creating-and-opening-files#file-attributes-and-directories
* Setting file compression state: https://learn.microsoft.com/en-us/windows/win32/fileio/compression-state

2024-12-31 17:43 UTC, eversinc33 commented
Very good points, I think this is the better approach. I will start implementing this in the new year and update this PR

2025-01-01 20:58 UTC, eversinc33 commented
Force pushed with the new approach.

![image](https://github.com/user-attachments/assets/e4be7f54-2aea-4913-b748-3089052d3292)

Disables compression on both the directory as well as the blockchain file if set. If not, continues silently. Let me know what you think.

2025-01-01 22:16 UTC, iamamyth commented on src/blockchain_db/lmdb/db_lmdb.cpp
> +  if (boost::filesystem::exists(filename) && !disable_ntfs_compression(filename))
The earlier logic creates the directory (~line 1337), so you shouldn't need to check for existence (the extra check doesn't add race protection, and you don't need race protection).

2025-01-01 22:21 UTC, iamamyth commented on src/blockchain_db/lmdb/db_lmdb.cpp
> +  if (boost::filesystem::exists(datafile) && !disable_ntfs_compression(datafile))
I would touch the file so that it always exists, otherwise the daemon might have a compressed db on first launch. Also, if disabling compression fails, I'd throw a DB_ERROR.

2025-01-01 22:28 UTC, iamamyth commented on src/blockchain_db/lmdb/db_lmdb.cpp
> +bool BlockchainLMDB::disable_ntfs_compression(const boost::filesystem::path& filepath) const
Would make this `static` and move it to precede open.

2025-01-02 13:33 UTC, eversinc33 commented
Thank you again for the great feedback. Please see the latest commit.

2025-01-02 21:10 UTC, iamamyth commented on src/blockchain_db/lmdb/db_lmdb.cpp
> +  boost::filesystem::ofstream(datafile.string()).close(); // touch the file to ensure it exists
I think you can simplify this to `ofstream(datafile)`, which avoids information loss from path->string conversion

2025-01-02 21:26 UTC, iamamyth commented
A clarification on handling directory-level compression for other reviewers: One could argue that if the directory already exists, the program should preserve its compression attribute; in fact, I suggested as much in earlier comments. However, upon further consideration, I think it makes sense to choose the most intrusive option (always uncompress the directory) because:

1. It helps ensure consistent daemon behavior (as bug reports, and the Windows docs themselves, have illustrated, Windows filesystem compression is unreliable and non-transparent).
2. If the choice proves unworkable, a future PR can downgrade it, whereas starting with the least intrusive option (mixed compression modes) needlessly adds complexity.

2025-01-02 22:58 UTC, iamamyth commented
Can you confirm that this modification runs normally on Windows and results in an an unencrypted data directory + db post-shutdown in the following startup scenarios?

* Empty data directory
    * Encrypted
    * Not encrypted
* Complete mainnet data directory
    * Encrypted
    * Not encrypted

2025-01-03 14:09 UTC, eversinc33 commented on src/blockchain_db/lmdb/db_lmdb.cpp
> +  boost::filesystem::ofstream(datafile.string()).close(); // touch the file to ensure it exists
Fixed.

2025-01-03 18:10 UTC, iamamyth commented
In most projects, I'd add tests for new behavior. Here, the tests ordinarily don't run on windows, so extra tests don't do much. If you want to add tests, you have two mutually exclusive options:

1. Add windows-only tests to tests/unit_test/blockchain_db.cpp (probably simpler and a technically reasonable choice).
2. Add windows-only functional tests to tests/functional_tests (reflects the regression/integration aspect of the tests).

2025-01-03 18:11 UTC, iamamyth approved these changes

2025-01-03 18:38 UTC, iamamyth commented
There's a failing build: It looks like you need to explicitly add:
```
#include <boost/filesystem/fstream.hpp>
```

2025-01-03 18:41 UTC, iamamyth requested changes
There's a failing build. It looks like you need to explicitly add:
```
#include <boost/filesystem/fstream.hpp>
```

Everything else looks good. Thanks for your work on this issue!

2025-01-03 18:42 UTC, iamamyth commented
One last thing: Probably a good idea to squash commits for merge.

2025-01-03 20:17 UTC, iamamyth approved these changes

2025-01-03 20:27 UTC, eversinc33 commented
Fixed and squashed. Thanks again for the good feedback!

2025-01-14 09:36 UTC, selsta approved these changes

2025-01-14 09:38 UTC, selsta commented
Please also open this PR against `release-v0.18` branch.

2025-01-14 14:42 UTC, tobtoht commented
Lots of extraneous whitespace in this patch.

2025-01-14 18:35 UTC, iamamyth commented
> Lots of extraneous whitespace in this patch.

@tobtoht Was this posted on the wrong PR? I don't see any extraneous whitespace.

2025-01-14 18:37 UTC, selsta commented
There are a lot of spaces at the end of some lines, would be good to fix before merging.

2025-01-14 18:45 UTC, nahuhh commented
It seems to emulate codestyle from 1377-1402

2025-01-14 18:50 UTC, iamamyth commented
Now I see the whitespace (using CLI), I think the github web UI got worse and made it really hard to see. @eversinc33 Can you remove the extraneous end-of-line whitespace and squash?

2025-01-14 20:10 UTC, eversinc33 commented
> Now I see the whitespace (using CLI), I think the github web UI got worse and made it really hard to see. @eversinc33 Can you remove the extraneous end-of-line whitespace and squash?

Sorry, not sure where that came from. Squashed and pushed

2025-01-14 20:12 UTC, eversinc33 commented
> Please also open this PR against `release-v0.18` branch.

See https://github.com/monero-project/monero/pull/9702

2025-01-15 05:16 UTC, selsta commented
@eversinc33 Could you check again? This line for example still has whitespaces at the end of the line.

https://github.com/monero-project/monero/pull/9664/files#diff-94841b820d7dfb0ef2f631d635c246ea152fba2cf868b62a0dc084f04e9e2f6cR1364

2025-01-15 07:31 UTC, eversinc33 commented
Weird. I force pushed again, can you check now?

2025-01-15 07:33 UTC, selsta approved these changes
Looks good now.

2025-01-15 07:36 UTC, 0xFFFC0000 approved these changes
Thanks. LGTM.

2025-01-18 11:04 UTC, merged